version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - '80:80'

  react-front:
    build:
      dockerfile: dev.Dockerfile
      context: ReactFront
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./ReactFront:/usr/app
    command: ["npm", "run", "start"]

  node-back:
    build:
      context: ./NodeBack
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./NodeBack:/usr/app
    command: ["npm", "run", "dev"]

  postgres:
    build:
      context: ./PostgresDb
      dockerfile: dev.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./PostgresDb/dev/data:/var/lib/postgresql/data
